# Setup
title:               Terry Li的小博客
tagline:             ''
description:         '一个普通程序员.'
url:                 ''
baseurl:             ''
paginate:            8
permalink:           pretty
future:              true

highlighter:         rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax


# About/contact
author:
  name:              Terry Li
  url:               
  email:             omretterry@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - Gruntfile.js
  - node_modules
  - scripts

collections:  
  collections_dir: collections
  leetcode-liner-data-structure:
    output: true
    permalink: /leetcode/liner-data-structure/:name
  leetcode-nonliner-data-structure:
    output: true
    permalink: /leetcode/nonliner-data-structure/:name
  leetcode-dp:
    output: true
    permalink: /leetcode/dp/:name
  leetcode-other: 
    output: true
    permalink: /leetcode/other/:name
  leetcode-contest:
    output: t rue
    permalink: /leetcode-contest/:name
  
